// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ9s7V8Jty5UWt2WvjOpWxbmYXg554XP4',
    appId: '1:407273410681:web:e277ac1f96e865b55104a8',
    messagingSenderId: '407273410681',
    projectId: 'doanlaptrinhandroid-83908',
    authDomain: 'doanlaptrinhandroid-83908.firebaseapp.com',
    databaseURL: 'https://doanlaptrinhandroid-83908-default-rtdb.firebaseio.com',
    storageBucket: 'doanlaptrinhandroid-83908.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtWZlIvqVvsK220di8C5xyXC04BapxBI8',
    appId: '1:407273410681:android:e11bc7ba5fe076005104a8',
    messagingSenderId: '407273410681',
    projectId: 'doanlaptrinhandroid-83908',
    databaseURL: 'https://doanlaptrinhandroid-83908-default-rtdb.firebaseio.com',
    storageBucket: 'doanlaptrinhandroid-83908.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPe2WItxUJ6RfmtRyBOJOoxZZ5DjbseTA',
    appId: '1:407273410681:ios:352dd23871753b3e5104a8',
    messagingSenderId: '407273410681',
    projectId: 'doanlaptrinhandroid-83908',
    databaseURL: 'https://doanlaptrinhandroid-83908-default-rtdb.firebaseio.com',
    storageBucket: 'doanlaptrinhandroid-83908.firebasestorage.app',
    iosBundleId: 'com.example.doAnLapTrinhAndroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPe2WItxUJ6RfmtRyBOJOoxZZ5DjbseTA',
    appId: '1:407273410681:ios:352dd23871753b3e5104a8',
    messagingSenderId: '407273410681',
    projectId: 'doanlaptrinhandroid-83908',
    databaseURL: 'https://doanlaptrinhandroid-83908-default-rtdb.firebaseio.com',
    storageBucket: 'doanlaptrinhandroid-83908.firebasestorage.app',
    iosBundleId: 'com.example.doAnLapTrinhAndroid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ9s7V8Jty5UWt2WvjOpWxbmYXg554XP4',
    appId: '1:407273410681:web:0d917fc3ee4ce5145104a8',
    messagingSenderId: '407273410681',
    projectId: 'doanlaptrinhandroid-83908',
    authDomain: 'doanlaptrinhandroid-83908.firebaseapp.com',
    databaseURL: 'https://doanlaptrinhandroid-83908-default-rtdb.firebaseio.com',
    storageBucket: 'doanlaptrinhandroid-83908.firebasestorage.app',
  );
}
